version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin1234
      - MYSQL_DATABASE=credit_db
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
  redis:
    image: redis:7-alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=admin:admin1234@tcp(mysql:3306)/credit_db?parseTime=true
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - mysql
      - redis
    entrypoint: ["/app/wait-for.sh", "mysql:3306", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  data-volume:
