// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: loan_limit.sql

package repository

import (
	"context"
)

const getLimit = `-- name: GetLimit :one
SELECT ` + "`" + `limit` + "`" + ` FROM loan_limit
WHERE customer_id = ? AND tenor = ?
`

type GetLimitParams struct {
	CustomerID string `json:"customer_id"`
	Tenor      int32  `json:"tenor"`
}

func (q *Queries) GetLimit(ctx context.Context, arg GetLimitParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getLimit, arg.CustomerID, arg.Tenor)
	var limit float64
	err := row.Scan(&limit)
	return limit, err
}
