// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type Customer struct {
	ID             string    `json:"id"`
	Nik            string    `json:"nik"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
	FullName       string    `json:"full_name"`
	LegalName      string    `json:"legal_name"`
	TempatLahir    string    `json:"tempat_lahir"`
	TanggalLahir   time.Time `json:"tanggal_lahir"`
	Gaji           float64   `json:"gaji"`
	PhotoKtp       string    `json:"photo_ktp"`
	FotoSelfie     string    `json:"foto_selfie"`
}

type LoanLimit struct {
	ID         string  `json:"id"`
	CustomerID string  `json:"customer_id"`
	Tenor      int32   `json:"tenor"`
	Limit      float64 `json:"limit"`
}

type PaymentDetail struct {
	ID            string    `json:"id"`
	TransactionID string    `json:"transaction_id"`
	Amount        float64   `json:"amount"`
	PaymentTime   time.Time `json:"payment_time"`
}

type Transaction struct {
	ID            string    `json:"id"`
	CustomerID    string    `json:"customer_id"`
	ProductName   string    `json:"product_name"`
	Price         float64   `json:"price"`
	Bunga         float64   `json:"bunga"`
	JumlahCicilan float64   `json:"jumlah_cicilan"`
	Tenor         int32     `json:"tenor"`
	AdminFee      float64   `json:"admin_fee"`
	CreatedAt     time.Time `json:"created_at"`
}
