// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment_details.sql

package repository

import (
	"context"
	"time"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO ` + "`" + `payment_details` + "`" + ` (
    id,
    transaction_id,
    amount,
    due_date,
    is_paid
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreatePaymentParams struct {
	ID            string    `json:"id"`
	TransactionID string    `json:"transaction_id"`
	Amount        float64   `json:"amount"`
	DueDate       time.Time `json:"due_date"`
	IsPaid        bool      `json:"is_paid"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.TransactionID,
		arg.Amount,
		arg.DueDate,
		arg.IsPaid,
	)
	return err
}
